### ISSUE TITLE
数据集图像

### ISSUE THREAD

**Issue by Aspirinkb** [Tencent/tencent-ml-images#13]
问题1：多少张图像链接在`train_urls.txt`里面？我下载`train_urls.txt`之后，看了一下，有**17609808**行，但是你们的文档说应该有**17,609,752**张图像才对。请问是我下载过程中出问题了，还是文档出现了错误？
问题2：`train_urls.txt`中的图像和`train_urls_and_index_from_imagenet.txt`中的图像到底是什么关系？没看懂文档什么意思。如果`train_urls.txt`中的链接失效了，应该去`train_urls_and_index_from_imagenet.txt`中找相应的有效链接吗？也就是我们需要自己根据下载时的情况监测链接是否有效？
谢谢

**Comment by wubaoyuan** [comment]
你好。
回答1： 我check了train_urls.txt， 的确是17,609,752 行。
你是在linux下打开的吗？在windows下我没有打开过，因为太大了，有没有是在windows下可能出现了格式变化。

回答2： 请看我们最新的readme, train_urls_and_index_from_imagenet.txt 对应的是
train_urls.txt的前10,706,941行，也就是来源于imagenet的，train_urls.txt其他是来源于open
images的urls.  我们建议，对于train_urls_and_index_from_imagenet.txt中的url，
直接从imagenet中下载相应的图像； 对于来源于open images中的url，可以用我们的代码直接下载。

希望对你有帮助！

Frank <notifications@github.com> 于2018年10月22日周一 下午2:34写道：
