### ISSUE TITLE
图像数据集

### ISSUE THREAD

**Issue by Aspirinkb** [Tencent/tencent-ml-images#14]
问题1：多少张图像链接在`train_urls.txt`里面？我下载`train_urls.txt`之后，看了一下，有**17609808**行，但是你们的文档说应该有**17,609,752**张图像才对。请问是我下载过程中出问题了，还是文档出现了错误？
问题2：`train_urls.txt`中的图像和`train_urls_and_index_from_imagenet.txt`中的图像到底是什么关系？没看懂文档什么意思。如果`train_urls.txt`中的链接失效了，应该去`train_urls_and_index_from_imagenet.txt`中找相应的有效链接吗？也就是我们需要自己根据下载时的情况监测链接是否有效？
谢谢

**Comment by wubaoyuan** [comment]
@Aspirinkb 
回答1： 我check了train_urls.txt， 的确是17,609,752 行。 你是在linux下打开的吗？在windows下我没有打开过，因为太大了，有没有可能是在windows下出现了格式变化。

回答2： 请看我们最新的README, train_urls_and_index_from_imagenet.txt 对应的是train_urls.txt的前10,706,941行，也就是来源于imagenet的，train_urls.txt的其他行是来源于open images的urls.  我们建议，对于train_urls_and_index_from_imagenet.txt中的url， 直接从imagenet中下载相应的图像； 对于来源于open images中的url，可以用我们的代码直接下载。

**Comment by Aspirinkb** [comment]
也就是说，对于ImageNet的图像，你们建议直接从其[ImageNet官网](http://image-net.org/download)选择**Download Original Images**下载原始图像？
我是在macOS系统中查看的`train_urls.txt`，并使用了两种方式：
1. `wc -l train_urls.txt`，显示有 17609808 行；
2. 在`VS Code`中打开，同样显示有  17609808 行，截图如下   
![VSCode](https://user-images.githubusercontent.com/5260197/47325173-3c017600-d695-11e8-81dc-77ee7e841304.png)
对于图像数量的问题，你们确定上传到百度网盘的版本和你们使用的版本一致吗？请问有MD5什么的查看下载是否和原始文件一致？最好提供一个校验值。

**Comment by wubaoyuan** [comment]
我们从百度硬盘上下载了一遍，再次确认 train_urls.txt 为17,609,752行，你可以在linux下查看下。

Frank <notifications@github.com> 于2018年10月23日周二 上午7:30写道：
