### ISSUE TITLE
The last 6,902,811 rows of train_urls.txt and the last 38,739 rows of val_urls.txt are URLs from ImageNet？？

### ISSUE THREAD

**Issue by idealboy** [Tencent/tencent-ml-images#20]
The last 6,902,811 rows of train_urls.txt and the last 38,739 rows of val_urls.txt are URLs from ImageNet.

it means：

The last 6,902,811 rows of train_urls.txt and the last 38,739 rows of val_urls.txt are URLs from OpenImage?

**Comment by wubaoyuan** [comment]
@idealboy You are right. Thanks a lot for indicating this typo. It is fixed now.
