### ISSUE TITLE
Some image index is Repeated

### ISSUE THREAD

**Issue by AmberCheng** [Tencent/tencent-ml-images#30]
Hi,

These days I try to download the data as your instruction. As for I already have the imagenet dataset, I just make a map with yout imagenet_index and my imagenet dataset. But after I have done the map, I find some imagenet index is repeated in your txt file. I wonder is it a right thing?

**Comment by wubaoyuan** [comment]
@AmberCheng You are right. We also find there are some repeated URLs from ImageNet, which is inconsistent with our training set. We are fixing it, and will update it soon.

**Comment by AmberCheng** [comment]
Thank you @wubaoyuan , I will close the issue.
