### ISSUE TITLE
Error when extracting features

### ISSUE THREAD

**Issue by rgedeon** [Tencent/tencent-ml-images#48]
I downloaded ckpt-resnet101-mlimages checkpoint and used the extract_feature.py script to extarct features as follows: 

python extract_feature.py --resnet_size=101 --data_format='NCWH' --visiable_gpu=0 --pretrain_ckpt=checkpoints/ckpt-resnet101-mlimages/model.ckpt --result=result.txt --images=imglist.txt

But I got the following error:

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [2048,1000] rhs shape= [2048,11166]
	 [[node save/Assign_6 (defined at extract_feature.py:67) ]]

**Comment by wubaoyuan** [comment]
@rgedeon  Note that there are two checkpoints. Please use "ckpt-resnet101-mlimages-imagenet"

**Comment by rgedeon** [comment]
@wubaoyuan  I fixed that but now I have this error:
feature-length:2048, feature=[0.31629637 0.         0.         ... 0.479185   0.         2.0601978 ]
Traceback (most recent call last):
 File "extract_feature.py", line 93, in <module>
   ffeat.write(sp[0] + "\t" + sp[1] + "\t" + " ".join([str(x) for x in list(feats)]) + '\n')
IndexError: list index out of range

**Comment by wubaoyuan** [comment]
That is a minor issue, please print the value for debugging.

rgedeon <notifications@github.com> 于2019年3月19日周二 下午6:18写道：

**Comment by rgedeon** [comment]
Yes the sp[1] is the out of range. 

how shall I prepare the images text file. Is it just one path per line?

**Comment by rgedeon** [comment]
I put the path then space then the file name then new line
