### ISSUE TITLE
Annotations?

### ISSUE THREAD

**Issue by FranciscoFlorezRevuelta** [Tencent/tencent-ml-images#65]
Hi,

I am not interested on the images but on the annotations. 

You mention that "The annotations of all URLs in ML-Images are stored in train_urls.txt and val_urls.txt". Where can I find these files?

Thanks

**Comment by wubaoyuan** [comment]
@FranciscoFlorezRevuelta  Actually "train_urls.txt " is split to two parts, imagenet and open-images. You can download them from the links under "Download Images", like "train_image_id_from_imagenet.txt (link 1, link 2)".
